# -*- coding: utf-8 -*-
"""#1_criando_um_histograma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KroiIpC1KAbngzNqLk-LM-71cal4yway
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 100

import numpy as np
import matplotlib.pyplot as plt

data = [1,2,5,4,3,6,7,3,2,4,7,5,5,4,6,6,3,5,4]
bins=6

plt.hist(data, bins=bins, density=False, edgecolor='w')
plt.show()

plt.hist(data, bins=bins, density=True, edgecolor='w')
plt.show()